events {}

http {

	# ssl_certificate /etc/nginx/ssl/server.crt;
    # ssl_certificate_key /etc/nginx/ssl/server.key;

    # ssl_protocols TLSv1.2 TLSv1.3;
    
    # ssl_prefer_server_ciphers on;
    # ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

	server {
		listen 80;
		server_name localhost;

		# MINE TYPE
		default_type  application/octet-stream;
		include       /etc/nginx/mime.types;			

		root /var/www/html;
		index index.php index.html index.nginx-debian.html;

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			# On définit comment séparer l'URL du script
			fastcgi_split_path_info ^(.+\.php)(/.+)$;
			
			# C'EST ICI : On utilise le NOM DU SERVICE défini dans le docker-compose
			fastcgi_pass wordpress:9000;
			
			# On définit le fichier par défaut
			fastcgi_index index.php;
			
			# On inclut les paramètres standards de FastCGI
			include fastcgi_params;
			
			# On indique le chemin réel du fichier dans le conteneur WordPress
			fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
			fastcgi_param PATH_INFO $fastcgi_path_info;
}
	}
}

# http {
# 	server {
#     listen 443 ssl;
#     server_name localhost;

#     ssl_certificate /etc/nginx/ssl/server.crt;
#     ssl_certificate_key /etc/nginx/ssl/server.key;

#     ssl_protocols TLSv1.2 TLSv1.3;
    
#     ssl_prefer_server_ciphers on;
#     ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

#     # location / {
#     #     root   /usr/share/nginx/html;
#     #     index  index.html;
#     # }
# }}