services:
  mariadb:
    container_name: mariadb
    build:
     context: ./requirements/mariadb
     dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - docker-network
    secrets:
      - wp_password
      - root_password
    restart: always
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_ROOT_PASSWORD: /run/secrets/root_password
      MARIADB_PASSWORD: /run/secrets/wp_password

  wordpress:
    depends_on:
      - mariadb
    build:
     context: ./requirements/wordpress/
     dockerfile: Dockerfile
    container_name: wordpress
    secrets:
      - wp_password
      - user_password
      - jojo_password
    volumes:
      - wp_data:/var/www/html
    restart: always
    networks:
      - docker-network
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: /run/secrets/wp_password
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      DOMAIN_NAME: ${DOMAIN_NAME}
      SITE_TITLE: ${SITE_TITLE}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: /run/secrets/user_password
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      JOJO_USER: ${JOJO_USER}
      JOJO_EMAIL: ${JOJO_EMAIL}
      JOJO_PASSWORD: /run/secrets/jojo_password

  nginx:
    depends_on:
      - wordpress
    build:
     context: ./requirements/nginx/
     dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html:ro
    networks:
      - docker-network
    restart: always

secrets:
  root_password:
    file: ../secrets/root_password.txt
  wp_password:
    file: ../secrets/wp_password.txt
  user_password:
    file: ../secrets/user_password.txt
  jojo_password:
    file: ../secrets/jojo_password.txt

networks:
  docker-network:
    driver: bridge

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      device: /home/kevwang/data/mariadb
      o: bind
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      device: /home/kevwang/data/wordpress
      o: bind
