services:
  db:
    container_name: db
    build:
     context: ./srcs/requirements/mariadb
     dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default
    secrets:
      - wp_password
      - root_password
  #   # restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_ROOT_PASSWORD: /run/secrets/root_password
      MARIADB_PASSWORD: /run/secrets/wp_password

  wordpress:
    depends_on:
      - db
    build:
     context: ./srcs/requirements/wordpress/
     dockerfile: Dockerfile
    container_name: wordpress
    secrets:
      - wp_password
      - user_password
    volumes:
      - wp_data:/var/www/html
    restart: always
    networks:
      - default
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: /run/secrets/wp_password
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      DOMAIN_NAME: ${DOMAIN_NAME}
      SITE_TITLE: ${SITE_TITLE}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: /run/secrets/user_password
      ADMIN_EMAIL: ${ADMIN_EMAIL}

  nginx:
    depends_on:
      - wordpress
    build:
     context: ./srcs/requirements/nginx/
     dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8443:443"
    volumes:
      - wp_data:/var/www/html:ro
    networks:
      - default
    restart: always

secrets:
  root_password:
    file: ./srcs/requirements/secrets/root_password.txt
  wp_password:
    file: ./srcs/requirements/secrets/wp_password.txt
  user_password:
    file: ./srcs/requirements/secrets/user_password.txt

networks:
  default:
    driver: bridge

volumes:
  db_data:
    name: db_data
  wp_data:
    name: wp_data

# volumes:
#   db_data:
#     name: db_data
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/kevwang/data/mariadb
#       o: bind
#   wp_data:
#     name: wp_data
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/kevwang/data/wordpress
#       o: bind