services:
  db:
    container_name: db
    image: mariadb:10.6
    build:
     context: ./srcs/requirements/mariadb
     dockerfile: Dockerfile
    volumes:
      # - ./srcs/requirements/mariadb/tools/setup.sh:/docker-entrypoint-initdb.d/setup.sh
      - db_data:/var/lib/mysql
    networks:
      - default
  #   # restart: unless-stopped
  #   # secrets:
  #   #  - my_secret
  #   env_file: 
  #    - path: ./.env
  #   environment:
  #     # MARIADB_ROOT_PASSWORD: rootpass
  #     # MARIADB_PASSWORD: pass
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}


  wordpress:
    depends_on:
      - db
    build:
     context: ./srcs/requirements/wordpress/
     dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    restart: always
    networks:
      - default
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_HOST: db:3306
    # environment:
    #   WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    #   WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    #   WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    #   WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}


  nginx:
    depends_on:
      - wordpress
    build:
     context: ./srcs/requirements/nginx/
     dockerfile: Dockerfile
    container_name: nginx
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - wp_data:/var/www/html:ro
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    restart: always

# secrets:
#  my_secret:
#   file: ./secrets/.env

networks:
  default:
    driver: bridge

volumes:
  db_data:
    name: db_data
  wp_data:
    name: wp_data